export const ADD='ADD'
export const REDUCE='REDUCE'
export const SET_MSG='SET_MSG'
export const SAVE_ARTICLE='SAVE_ARTICLE'





/*===============*/
//loading
export const SHOW_LOADING='SHOW_LOADING'
export const HIDE_LOADING='HIDE_LOADING'
//article
export const GET_ARTICLES='GET_ARTICLES_'
export const GET_ARTICLES_SUCCESS='GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAIL='GET_ARTICLES_FAIL'
//articleDetail
export const GET_ARTICLE_BY_ARTICLEID_SUCCESS='GET_ARTICLE_BY_ARTICLEID_SUCCESS'
export const GET_ARTICLE_BY_ARTICLEID_FAIL='GET_ARTICLE_BY_ARTICLEID_FAIL'
//message
export const SHOW_MESSAGE='SHOW_MESSAGE'
//login
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAIL='LOGIN_FAIL'
//articleCenter
export const GET_ARTICLES_BY_CATALOGID='GET_ARTICLES_BY_CATALOGID'
export const GET_ARTICLES_BY_CATALOGID_SUCCESS='GET_ARTICLES_BY_CATALOGID_SUCCESS'
export const GET_ARTICLES_BY_CATALOGID_FAIL='GET_ARTICLES_BY_CATALOGID_FAIL'

export const GET_CATALOGS='GET_CATALOGS'
export const GET_CATALOGS_SUCCESS='GET_CATALOGS_SUCCESS'
export const GET_CATALOGS_FAIL='GET_CATALOGS_FAIL'
export const SAVE_ARTICLES_BY_CATALOGID='SAVE_ARTICLES_BY_CATALOGID'

export const DELETE_ARTICLE='DELETE_ARTICLE'
export const DELETE_ARTICLE_SUCCESS='DELETE_ARTICLE_SUCCESS'
export const DELETE_ARTICLE_FAIL='DELETE_ARTICLE_FAIL'

export const SET_PUBLISH_STATUS='SET_PUBLISH_STATUS'
export const SET_PUBLISH_STATUS_SUCCESS='SET_PUBLISH_STATUS_SUCCESS'
export const SET_PUBLISH_STATUS_FAIL='SET_PUBLISH_STATUS_FAIL'

export const SET_CURRENT_CATALOGID='SET_CURRENT_CATALOGID'
//publish
export const PUBLISH='PUBLISH'
export const PUBLISH_SUCCESS='PUBLISH_SUCCESS'
export const PUBLISH_FAIL='PUBLISH_FAIL'
